# This is a basic workflow to help you get started with Actions

name: Github Pages CI

on:
  push:
    branches:
    - 'master'
    tags-ignore:
    - '**'
    paths-ignore:
    - '**/*.adoc'
    - '**/*.md'
    - '.github/*.yml'
    - 'docs/**'
  workflow_dispatch:
    # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
- name: Deploy
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: ./docs/
